{
    "KPlugin": {
        "Description": "Kontact KNotes Plugin",
        "Description[ar]": "ملحقة «ملاحظاتك» لِ‍«متراسلك»",
        "Description[bg]": "Приставка KNotes за Kontact",
        "Description[ca@valencia]": "Connector de KNotes de Kontact",
        "Description[ca]": "Connector del KNotes del Kontact",
        "Description[de]": "KNotes-Modul für Kontact",
        "Description[el]": "Πρόσθετο KNotes του Kontact",
        "Description[en_GB]": "Kontact KNotes Plugin",
        "Description[es]": "Complemento de KNotes para Kontact",
        "Description[eu]": "Kontact-en KNotes plugin-a",
        "Description[fi]": "Kontactin KNotes-liitännäinen",
        "Description[fr]": "Module externe « KNotes » pour Kontact",
        "Description[ia]": "Plug-in de Kontact KNotes",
        "Description[it]": "Estensione per Kontact di KNotes",
        "Description[ko]": "Kontact KNotes 플러그인",
        "Description[nl]": "Kontact KNotes-plug-in",
        "Description[pl]": "Wtyczka Kontact do współpracy z KNotatkami",
        "Description[pt]": "'Plugin' do KNotes para o Kontact",
        "Description[pt_BR]": "Plugin do KNotes para o Kontact",
        "Description[ru]": "Заметки",
        "Description[sl]": "Vstavek Kontact za KNotes",
        "Description[sv]": "Kontacts insticksprogram för Knotes",
        "Description[tr]": "Kontact KNotes Eklentisi",
        "Description[uk]": "Додаток приміток (KNotes) Kontact",
        "Description[x-test]": "xxKontact KNotes Pluginxx",
        "EnabledByDefault": true,
        "Icon": "view-pim-notes",
        "Id": "kontact_knotesplugin",
        "License": "LGPL",
        "Name": "Popup Notes",
        "Name[ar]": "ملاحظات منبثقة",
        "Name[bg]": "Лепящи се бележки",
        "Name[bs]": "Iskočne napomene",
        "Name[ca@valencia]": "Notes emergents",
        "Name[ca]": "Notes emergents",
        "Name[cs]": "Vyskakovací poznámky",
        "Name[da]": "Pop op-noter",
        "Name[de]": "Haftnotizen",
        "Name[el]": "Αναδυόμενα σημειώματα",
        "Name[en_GB]": "Popup Notes",
        "Name[eo]": "Glunotoj",
        "Name[es]": "Notas emergentes",
        "Name[et]": "Sedelid",
        "Name[eu]": "Ohar gainerakorrak",
        "Name[fi]": "Ponnahdusviestit",
        "Name[fr]": "Notes",
        "Name[ga]": "Preabnótaí",
        "Name[gl]": "Notas emerxentes",
        "Name[hu]": "Jegyzetlapok",
        "Name[ia]": "Notas de popup",
        "Name[it]": "Note a comparsa",
        "Name[ja]": "ポップアップメモ",
        "Name[kk]": "Қалқымалы жазбалар",
        "Name[km]": "ចំណាំ​លេច​ឡើង",
        "Name[ko]": "팝업 노트",
        "Name[lt]": "Lipnūs lapeliai",
        "Name[lv]": "Piezīmju lapiņas",
        "Name[mr]": "पॉपअप नोंदी",
        "Name[nb]": "Sprettopp-notater",
        "Name[nds]": "Opduk-Notizen",
        "Name[nl]": "Popup notities",
        "Name[nn]": "Sprettoppnotat",
        "Name[pa]": "ਪੋਪਅੱਪ ਨੋਟਿਸ",
        "Name[pl]": "Żółte karteczki",
        "Name[pt]": "Notas",
        "Name[pt_BR]": "Notas instantâneas",
        "Name[ro]": "Notițe",
        "Name[ru]": "Заметки",
        "Name[sk]": "Vyskakujúce poznámky",
        "Name[sl]": "Pojavna sporočilca",
        "Name[sr@ijekavian]": "Искачуће биљешке",
        "Name[sr@ijekavianlatin]": "Iskačuće bilješke",
        "Name[sr@latin]": "Iskačuće beleške",
        "Name[sr]": "Искачуће белешке",
        "Name[sv]": "Anteckningslappar",
        "Name[th]": "บันทึกย่อแบบป๊อปอับ",
        "Name[tr]": "Açılır Notlar",
        "Name[ug]": "سەكرىمە ئىزاھلار",
        "Name[uk]": "Записник",
        "Name[wa]": "Aspitantès notes",
        "Name[x-test]": "xxPopup Notesxx",
        "Name[zh_CN]": "弹出便笺",
        "Name[zh_TW]": "彈出式便條",
        "ServiceTypes": [
            "Kontact/Plugin",
            "KPluginInfo"
        ],
        "Version": "0.1",
        "Website": "https://userbase.kde.org/KNotes"
    },
    "X-KDE-ConfigModuleNamespace": "pim@QT_MAJOR_VERSION@/kcms/knotes/",
    "X-KDE-KontactPartExecutableName": "knotes",
    "X-KDE-KontactPluginHasSummary": true,
    "X-KDE-KontactPluginVersion": 11,
    "X-KDE-Weight": 600
}
