# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'pim/akonadi' : '@same'
    'pim/akonadi-notes' : '@same'
    'pim/akonadi-search' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kmime' : '@same'
    'pim/kontactinterface' : '@same'
    'pim/pimcommon' : '@same'
    'pim/grantleetheme' : '@same'
    'frameworks/kcompletion': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kdnssd': '@latest-kf6'
    'frameworks/kglobalaccel': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kitemmodels': '@latest-kf6'
    'frameworks/kitemviews': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/knewstuff': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/knotifyconfig': '@latest-kf6'
    'frameworks/kparts': '@latest-kf6'
    'frameworks/ktextwidgets': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/ktexttemplate': '@latest-kf6'
    'frameworks/kstatusnotifieritem': '@latest-kf6'
    'libraries/ktextaddons': '@latest-kf6'

Options:
  cmake-options: "-DAKONADI_RUN_MYSQL_ISOLATED_TESTS=FALSE -DAKONADI_RUN_PGSQL_ISOLATED_TESTS=FALSE -DAKONADI_RUN_SQLITE_ISOLATED_TESTS=FALSE"
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
