# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'pim/akonadi' : '@latest-kf6'
    'pim/akonadi-notes' : '@latest-kf6'
    'pim/akonadi-search' : '@latest-kf6'
    'pim/kcalutils' : '@latest-kf6'
    'pim/kmime' : '@latest-kf6'
    'pim/kontactinterface' : '@latest-kf6'
    'pim/kpimtextedit' : '@latest-kf6'
    'pim/libkdepim' : '@latest-kf6'
    'pim/pimcommon' : '@latest-kf6'
    'pim/grantleetheme' : '@latest-kf6'
    'frameworks/kcompletion': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kdnssd': '@latest-kf6'
    'frameworks/kglobalaccel': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kitemmodels': '@latest-kf6'
    'frameworks/kitemviews': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/knewstuff': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/knotifyconfig': '@latest-kf6'
    'frameworks/kparts': '@latest-kf6'
    'frameworks/ktextwidgets': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'libraries/ktextaddons': '@latest-kf6'
    'libraries/ktexttemplate': '@latest-kf6'
